apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-pvc
  namespace: pipeline-pioneers
  labels:
    app: pipeline-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi



