{
 "title": "Pipeline Pioneers",
 "description": "For the awesome people who are the Pipeline Pioneers Members.",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Monitor for Banking Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-(sum(pipeline_pioneers_500_server_error_total) / on() sum(pipeline_pioneers_http_requests_total) * 100)"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pipeline_pioneers_500_server_error_total) / on() sum(pipeline_pioneers_http_requests_total) * 100"
    }
   ]
  },
  {
   "title": "Percentage of requests under 200ms",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum(pipeline_pioneers_high_latency_counter_total) / (sum(pipeline_pioneers_http_requests_total) -  sum(pipeline_pioneers_500_server_error_total)) * 100)"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jetty_server_requests_seconds_sum{application=\"Pipeline-Bank\", outcome=\"SUCCESS\", uri != \"NOT_FOUND\", uri != \"/metrics\"}) / on () sum(jetty_server_requests_seconds_count{application=\"Pipeline-Bank\", outcome=\"SUCCESS\", uri != \"NOT_FOUND\", uri != \"/metrics\"})"
    }
   ]
  },
  {
   "title": "Average Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(container_memory_working_set_bytes{name!~\"POD\", namespace = \"pipeline-pioneers\",  pod != \"pipeline-db\"\r\n } / (8*1000000*134.217728)) by (pod)) * 100"
    }
   ]
  },
  {
   "title": "Total Memory Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace = \"pipeline-pioneers\", resource=\"memory\"}) / 1000000"
    }
   ]
  },
  {
   "title": "Memory Utilization per Pod",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{name!~\"POD\", namespace = \"pipeline-pioneers\",  pod != \"pipeline-db\"\r\n } / (8*1000000*134.217728)) by (pod)) * 100"
    }
   ]
  },
  {
   "title": "Pod Memory Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace = \"pipeline-pioneers\", resource=\"memory\"}) / 1000000"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum (rate (container_cpu_usage_seconds_total{namespace = \"pipeline-pioneers\", container = \"pipeline-pioneers-deployment\"}[1m])) by (pod))"
    }
   ]
  },
  {
   "title": "Total CPU Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namespace_cpu:kube_pod_container_resource_limits:sum{namespace = \"pipeline-pioneers\"}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace = \"pipeline-pioneers\",container = \"pipeline-pioneers-deployment\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "Pod CPU Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namespace_cpu:kube_pod_container_resource_limits:sum{namespace = \"pipeline-pioneers\"}/3"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization per Pod",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(system_cpu_usage{application=\"Pipeline-Bank\"}[30s]) * 100\r\n"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{application=\"Pipeline-Bank\"}"
      }
     ]
    },
    {
     "title": "Different CPU Usage by Namespace (see how it compares)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",namespace =\"pipeline-pioneers\"}[1m])) by (namespace)"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_memory_usage_bytes{namespace=\"pipeline-pioneers\"}[1m] ) / 1000000)"
      }
     ]
    },
    {
     "title": "Network Utilization Recieving",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace = \"pipeline-pioneers\"}[5m])) by (pod)"
      }
     ]
    }
   ]
  }
 ]
}