pipeline {
	agent any
	environment {
		registry='zachburnett/pipeline-pioneers'
		dockerImage=''
		dockerHubCredentials='docker' // This is in Jenkins credentials
	}
	stages {
		stage("Maven build"){
				steps {
					sh '/usr/bin/mvn -f BankAppP2/pom.xml clean package'
				}
			}
		stage("Docker build") {
			steps {
				script {
					dockerImage = docker.build("$registry", "./BankAppP2")
				}
			}
		}
		stage("pushing to Docker Hub") {
			steps {
				script {
					docker.withRegistry('',dockerHubCredentials) {
						dockerImage.push("$currentBuild.number")
						dockerImage.push("latest")
					}
				}
			}
		}
		stage("Deploying to Kubernetes") {
			steps{
				sh "kubectl set image -n pipeline-pioneers deployment/pipeline-pioneers-deployment pipeline-pioneers-deployment=$registry$currentBuild.number"
			}
		}
	}
}
